---
deployment:
 tasks:
  - export DEPLOYPATH=/home/izbsddgh/public_html/
  - /bin/cp index.html $DEPLOYPATH
  - /bin/cp referee-home.php $DEPLOYPATH
  - /bin/cp connect.php $DEPLOYPATH
  - /bin/cp -r css $DEPLOYPATH
